name: flutter_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI / Animation
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # # FIXED âœ… (very important)
  # fluttertoast: 8.2.8

  # Image picker
  image_picker: ^1.1.2

  # State management
  provider: ^6.1.2

  # API integration
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/
